name: Go

on:
  push:
    branches: [ main ]
    paths-ignore: 
      - '.github/**'
      - 'README.md'
      - 'LICENSE'
      - '*.code-workspace'    
  pull_request:
    branches: [ main ]
    paths-ignore: 
      - '.github/**'
      - 'README.md'
      - 'LICENSE'
      - '*.code-workspace'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
