name: Logic Calculator CLI Continuous Integration

on:
  push:
    branches: [ main ]
    paths:
    - logic-calculator-cli/**
    - .github/workflows/logic-calculator-cli-CI.yml
  pull_request:
    branches: [ main ]
    paths:
    - logic-calculator-cli/**
    - .github/workflows/logic-calculator-cli-CI.yml

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: WhereAmI
      run: pwd
      working-directory: logic-calculator-cli
    - name: Build
      run: go build -v ./
      working-directory: ./logic-calulator-cli

    - name: Test
      run: go test -v ./
      working-directory: ./logic-calculator-cli
