name: usersApi CI

on:
  push:
    branches: [ main ]
    paths:
    - gosaml/**
    - .github/workflows/gosaml.yml
  pull_request:
    branches: [ main ]
    paths:
    - usersApi/**
    - .github/workflows/usersApi.yml

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Build
      run: go build -v ./...
      working-directory: usersApi

    - name: Test
      run: go test -v ./...
      working-directory: usersApi
